* handle connection refused * worker script

diff --git a/dist/distribute-rpyc-iter/samples/worker b/dist/distribute-rpyc-iter/samples/worker
--- a/dist/distribute-rpyc-iter/samples/worker
+++ b/dist/distribute-rpyc-iter/samples/worker
@@ -1,16 +1,26 @@
-#!/bin/bash
-# helper script to start a worker on a remote machine. copy this file to each worker machine.
-# just set your work folder correctly (replace myuser)
+#!/bin/zsh
+# helper script to start a worker. copy this file to each worker machine.
+# just set your work folder correctly (replace myuser and mymachine (with the "local" machine (or client))
 # the script would be the same on all worker machines. except the worker-x.json file (needs to be unique to each worker)
+# Also for the local machine, just comment out the mkdir and mount commands
 
-# these 4 lines are only needed on remote workers, comment them out on local
-mkdir -p /Users/myuser/work/
-mount_smbfs //myuser@client-machine/myuser/work/ /Users/myuser/work/
-#used for ios building
-mkdir -p /Users/myuser/Library/Developer/Xcode/
-mount_smbfs //myuser@client-machine/myuser/Library/Developer/Xcode/ /Users/myuser/Library/Developer/Xcode/
+# these lines are only needed on remote workers, comment them out on local
+umount ./work
+umount ./Library/Developer/Xcode
 
-pushd /Users/myuser/work/dist/ || exit
+mkdir -p ./work
+mkdir -p ./Library/Developer/Xcode
+
+mount_smbfs //worker@mymachine/worker/work/ /Users/myuser/work/
+# this one is used for ios build
+mount_smbfs //worker@mymachine/myuser/Library/Developer/Xcode/ /Users/myuser/Library/Developer/Xcode/
+
+# sshfs using fuse is not working properly atm, and might lock you out due to too many failed attempts, needs more testing
+#sshfs myuser@mymachine:work ./work
+#sshfs myuser@mymachine:Library/Developer/Xcode ./Library/Developer/Xcode
+# end of remote worker lines
+
+pushd /Users/myuser/work/utils/dist/rel || exit
 
 # you can remove the "nice" on your machine
 nice ./worker.py ./worker-x.json
